#!/bin/sh

# make sure we never run 2 rsync at the same time
lockfile="/tmp/alpine-mirror.lock"
if [ -z "$flock" ] ; then
  exec env flock=1 flock -n $lockfile "$0" "$@"
fi

src="$ALPINE_REPO"
dest="$REPO"

mkdir -p "$dest"
/usr/bin/rsync \
	--chmod=ugo+rwX \
	--verbose \
	--archive \
	--update \
	--hard-links \
	--delete \
	--human-readable \
	--delete-after \
	--delay-updates \
	--timeout=600 \
	$exclude \
	"$src" "$dest"
